name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - name: Merge coverage results
      run: npm run nyc:merge:playwright
    - name: Generate coverage report
      run: npm run nyc:report
    - name: Upload Playwright coverage report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-coverage
        path: ./coverage/playwright-final.json
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  playwright-tests-finished:
    name: Playwright tests finished
    runs-on: [self-hosted]
    needs:
      - test
    steps:
      - name: Say thank you to Playwright
        run: echo "All Playwright tests finished, now code coverage results could be collected"
        id: thanks-to-playwright-tests
